version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".gdbinit",
 ".gitignore",
 ".tool-versions",
 "CHANGELOG.md",
 "demo/fwup.conf",
 "README.md",
 "REUSE.toml",
 "run_qemu.sh",
 "run_qemu_gdb.sh"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "0BSD"

# Linux image for the demo
[[annotations]]
path = [
 "demo/Image"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Various"
SPDX-License-Identifier = "GPL-2.0-only"

# crc32.c
[[annotations]]
path = [
 "src/crc32.c"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "1986 Gary S. Brown"
SPDX-License-Identifier = "LicenseRef-GaryBrown1986"

# nanoprintf.h
[[annotations]]
path = [
 "src/nanoprintf.h"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Charles Nicholson <charles.nicholson+nanoprintf@gmail.com>"
SPDX-License-Identifier = "0BSD OR Unlicense"



